steps = 1e3
print_every = 1e4
print_trajectory_every = 1e6
N = 64
dt = 1e-6
initial_density = 2e-5
free_energy = "generic_wertheim"
dx = 10
k = 1e6
seed = 123456

[mobility]
type = "regularised"
rho_min = 1e-5

[generic_wertheim]
B2 = 2190

[[generic_wertheim.species]]
patches = [0, 0, 0, 0]

[[generic_wertheim.species]]
patches = [1, 1, 1, 1]

[[generic_wertheim.species]]
patches = [0, 0, 1, 1]

[[generic_wertheim.deltas]]
interaction = "0-0"
T = 293.15
deltaH = -42200
deltaS = -119.1
salt = 0.5
sticky_size = 6

[[generic_wertheim.deltas]]
interaction = "1-1"
T = 293.15
deltaH = -42400
deltaS = -120.6
salt = 0.5
sticky_size = 6
