use_CUDA = true
steps = 1e9
print_every = 1e4
print_trajectory_every = 1e6
N = 128
dt = 6e-6
distance_scaling_factor = 10
initial_density = 2e-6
free_energy = "generic_wertheim"
dx = 10
k = 1e6
seed = 12346

[mobility]
type = "regularised"
rho_min = 1e-7

[generic_wertheim]
allow_unspecified_B2s = false

[[generic_wertheim.species]]
patches = [0, 0, 0, 1]

[[generic_wertheim.species]]
patches = [2, 2]

[[generic_wertheim.B2s]]
interaction = "0-0"
value = 2190

[[generic_wertheim.B2s]]
interaction = "1-1"
value = 2190

[[generic_wertheim.B2s]]
interaction = "0-1"
value = 2190

[[generic_wertheim.deltas]]
interaction = "0-0"
T = 296
deltaH = -42200
deltaS = -119.1
salt = 0.5
sticky_size = 6

[[generic_wertheim.deltas]]
interaction = "1-2"
T = 296
deltaH = -26000
deltaS = -43.6
salt = 1.0
sticky_size = 1
