use_CUDA = true
steps = 1e9
print_every = 1e4
print_trajectory_every = 1e6
N = 64
dt = 6e-6
distance_scaling_factor = 10
initial_density = 2e-6
free_energy = "ricci"
dx = 10
k = 1e6
seed = 12346

[mobility]
type = "regularised"
rho_min = 1e-7

[ricci]
B2 = 2190

[ricci.delta_00]
T = 296
deltaH = -42200
deltaS = -119.1
salt = 0.5
sticky_size = 6

[ricci.delta_12]
T = 296
deltaH = -26000
deltaS = -43.6
salt = 1.0
sticky_size = 1
